android: enable AMDGPU targets for r600g with on-disk shader cache
Required to support shader disk cache for r600g, due to mesa commit
3bbbb63 "automake: r600: radeonsi: correctly manage libamd_common.la linking"

Fixes the following mesa build error when building r600g w/o radeonsi,
when llvm in used due to swrast llvmpipe:

external/mesa/src/util/disk_cache.h:52: error: undefined reference to 'LLVMInitializeAMDGPUTargetInfo'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

LLVMInitializeAMDGPUTargetInfo is used in src/gallium/drivers/radeon/r600_pipe_common.c:868:
			if (disk_cache_get_function_timestamp(LLVMInitializeAMDGPUTargetInfo,