android: remove terminfo dependency
This change is required to avoid following building errors:

host C++: libLLVMExecutionEngine <= external/llvm/lib/ExecutionEngine/ExecutionEngineBindings.cpp
external/llvm/lib/Support/Unix/Process.inc:357: error: undefined reference to 'setupterm'
external/llvm/lib/Support/Unix/Process.inc:375: error: undefined reference to 'tigetnum'
external/llvm/lib/Support/Unix/Process.inc:379: error: undefined reference to 'set_curterm'
external/llvm/lib/Support/Unix/Process.inc:380: error: undefined reference to 'del_curterm'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
build/core/host_executable_internal.mk:34: recipe for target 'out/host/linux-x86/obj/EXECUTABLES/llvm-tblgen_intermediates/llvm-tblgen' failed
make: *** [out/host/linux-x86/obj/EXECUTABLES/llvm-tblgen_intermediates/llvm-tblgen] Error 1
make: *** Waiting for unfinished jobs....