android: fix AMDGPU asm parser build
With mesa commit 24d4fbe "radeonsi: strengthen emit_optimization_barrier"
AMDGPU asm parser is used and its initialization causes mesa build error:

external/mesa/src/gallium/drivers/radeonsi/si_shader_tgsi_setup.c:130:
error: undefined reference to 'LLVMInitializeAMDGPUAsmParser'

In nougat-x86 branch (llvm 3.8) AMDGPU asm parser Android.mk,
source and tblgen variables need an underscore, to fix a typo,
and tblgen list is updated to avoid the following build errors:

external/llvm/lib/Target/AMDGPU/AsmParser/../MCTargetDesc/AMDGPUMCTargetDesc.h:
fatal error: 'AMDGPUGenRegisterInfo.inc' file not found
fatal error: 'AMDGPUGenInstrInfo.inc' file not found
fatal error: 'AMDGPUGenSubtargetInfo.inc' file not found

Fixes: f223f03 "android: enable support for AMDGPU targets for radeonsi"