android: update sources file names for llvm60
*SRC_FILES lists are aligned as per Cmakelist.txt files,
to avoid building errors due to changes in codebase

e.g. AMDGPUCodeObjectMetadata.cpp => AMDGPUMetadata.cpp

ninja: error: 'external/llvm60/lib/Support/AMDGPUCodeObjectMetadata.cpp',
needed by 'out/host/linux-x86/obj/STATIC_LIBRARIES/libLLVM60Support_intermediates/AMDGPUCodeObjectMetadata.o',
missing and no known rule to make it

or new missing sources:

external/llvm60/utils/TableGen/CodeGenDAGPatterns.cpp:88: error: undefined reference to 'llvm::ValueTypeByHwMode: